[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    #"-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tdefmt.x",

    # Code optimizations
    #"-Z", "trap-unreachable=no",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F429ZITx with your chip as listed in `probe-run --list-chips`
runner = "probe-rs run --chip LPC55S69JBD100 --probe 1fc9:0132 --protocol swd"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"