[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    #"-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tdefmt.x",

    # Code optimizations
    #"-Z", "trap-unreachable=no",
    #"-C", "inline-threshold=5",
    #"-C", "no-vectorize-loops",

    # Fixes LLVM bug on function outlining
    "-C", "llvm-args=--enable-machine-outliner=never",
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip LPC55S69JBD100 --probe 1fc9:0132 --protocol swd --no-location"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"